<?php

namespace MagicWordBundle\Repository;

/**
 * GameRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFinished($round)
    {
        $em = $this->_em;
        $dql = 'SELECT a FROM MagicWordBundle\Entity\Activity a
                WHERE a.round = :round
                AND a.endDate IS NOT NULL
                ORDER BY a.points DESC, a.duration DESC';

        $query = $em->createQuery($dql);
        $query->setParameter('round', $round);

        return $query->getResult();
    }
}
