<?php

namespace MagicWordBundle\Repository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoundableRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByGridAndCriteria($grid, $objective)
    {
        $em = $this->_em;
        $dql = 'SELECT f FROM MagicWordBundle\Entity\FoundableForm f JOIN f.inflections i JOIN i.lemma l WHERE f.grid = :grid';

        $dql .= $objective->getCategory()
            ? ' AND l.category = '.$objective->getCategory()->getId()
            : '';

        $dql .= $objective->getNumber()
                ? ' AND i.number = '.$objective->getNumber()->getId()
                : '';

        $dql .= $objective->getGender()
                ? ' AND i.gender = '.$objective->getGender()->getId()
                : '';

        $dql .= $objective->getPerson()
                ? ' AND i.person = '.$objective->getPerson()->getId()
                : '';

        $dql .= $objective->getTense()
                ? ' AND i.tense = '.$objective->getTense()->getId()
                : '';

        $dql .= $objective->getMood()
                ? ' AND i.mood = '.$objective->getMood()->getId()
                : '';

        $query = $em->createQuery($dql);
        $query->setParameter('grid', $grid);

        return $query->getResult();
    }
}
