<?php

namespace MagicWordBundle\Repository;

use MagicWordBundle\Entity\Player;
use MagicWordBundle\Entity\Language;

/**
 * GameRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotPlayedForTraining(Player $user, Language $language)
    {
        $em = $this->_em;
        $dql = "SELECT game FROM MagicWordBundle\Entity\Game game
                LEFT JOIN game.rounds r
                WHERE r.language = :language
                AND game INSTANCE OF 'MagicWordBundle\Entity\GameType\Training'
                AND NOT EXISTS(
                    SELECT a FROM MagicWordBundle\Entity\Activity a
                    WHERE a.round = r
                    AND a.player = :user
                )";

        $query = $em->createQuery($dql);
        $query->setParameter('user', $user)
              ->setParameter('language', $language)
              ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
