<?php

namespace MagicWordBundle\Repository;

/**
 * GameRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnfinished($user)
    {
        $em = $this->_em;
        $dql = 'SELECT g.id FROM MagicWordBundle\Entity\Game g
                JOIN g.rounds rounds
                WHERE EXISTS (
                    SELECT a FROM MagicWordBundle\Entity\Activity a
                    WHERE a.round  = rounds
                    AND a.player = :user
                    AND a.endDate is null
                )';

        $query = $em->createQuery($dql);
        $query->setParameter('user', $user->getId());

        return $query->getResult();
    }
}
