<?php

namespace MagicWordBundle\Repository;

/**
 * GridRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralParametersRepository extends \Doctrine\ORM\EntityRepository
{
    public function get()
    {
        $em = $this->_em;
        $dql = "SELECT g FROM MagicWordBundle\Entity\GeneralParameters g";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
