<?php

namespace MagicWordBundle\Repository;

/**
 * GridRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotPlayedForTraining($user)
    {
        $em = $this->_em;
        $dql = 'SELECT g FROM MagicWordBundle\Entity\Grid g
                WHERE g.language = :language
                AND NOT EXISTS(
                    SELECT a FROM MagicWordBundle\Entity\Activity a
                    LEFT JOIN a.round r
                    WHERE r.grid = g
                    AND a.player = :user
                )';

        $query = $em->createQuery($dql);
        $query->setParameter('user', $user)
              ->setParameter('language', $user->getLanguage())
              ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
