<?php

namespace MagicWordBundle\Repository;

/**
 * GridRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotPlayedForTraining($language)
    {
        $em = $this->_em;
        $dql = 'SELECT g FROM MagicWordBundle\Entity\Grid g
                    WHERE g.language = :language';
                    // ajouter une sousrequete qui tape dans les traces et qui vérifie que c'est une grille d'entrainement
                    // non jouée encore par le joueur

        $query = $em->createQuery($dql);
        $query->setParameter('language', $language)
              ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
