<?php

namespace MagicWordBundle\Repository;

/**
 * GridRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PDOSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastSessions($threshold)
    {
        $limit = time() - $threshold;

        $dql = 'SELECT s FROM MagicWordBundle:PDOSession s
                WHERE s.session_time >= ?1
                ORDER BY s.session_time DESC';

        $query = $this->_em->createQuery($dql);
        $query->setParameter(1, $limit);
        $sessions = $query->getResult();

        return $sessions;
    }
}
