<?php

namespace MagicWordBundle\Repository;

/**
 * RoundRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotPlayedYet($massive, $user)
    {
        $em = $this->_em;
        $dql = 'SELECT r FROM MagicWordBundle\Entity\Round r
                WHERE r.game = :massive
                AND NOT EXISTS (
                    SELECT a FROM MagicWordBundle\Entity\Activity a
                    WHERE a.player = :user
                    AND a.round = r
                    AND a.endDate IS NOT NULL
                )
                ORDER BY r.displayOrder ASC';

        $query = $em->createQuery($dql);
        $query->setParameter('massive', $massive)
            ->setParameter('user', $user)
             ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }
}
