<?php

namespace MagicWordBundle\Repository;

/**
 * WordboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordboxRepository extends \Doctrine\ORM\EntityRepository
{
}
