imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MagicWordBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    profilepic_directory: '%kernel.root_dir%/../web/upload/profilepic'

framework:
    #esi:             ~
    translator:      { enabled: true, fallbacks: [fr] }
    default_locale: fr
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:    session.handler.pdo
        name: "mw"
        cookie_lifetime: 0
        gc_maxlifetime: 7200
    fragments:       ~
    http_method_override: true
    assets:
        version: v20170521A
        packages:
            noversion:
                version: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:dbname=%database_name%'
            - { db_table:  session_pdo, db_username: %database_user%, db_password: %database_password% }

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
            lexicon:
                driver:   pdo_mysql
                host:     "%database_host2%"
                port:     "%database_port2%"
                dbname:   "%database_name2%"
                user:     "%database_user2%"
                password: "%database_password2%"
                charset:  UTF8
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                query_cache_driver: apc
                result_cache_driver: apc
                metadata_cache_driver: apc
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    MagicWordBundle: ~
                    InnovaLexiconBundle: ~
            lexicon:
                connection: lexicon
                mappings:
                    InnovaLexiconBundle:
                        mapping: true
                        is_bundle: true
                        type: annotation

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MagicWordBundle\Entity\Player

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [MagicWordBundle]
        directories: ["%kernel.root_dir%/../src"]
