innova_wiktionary:
    resource: "@InnovaWiktionaryBundle/Resources/config/routing.yml"
    prefix:   /

magic_word:
    resource: "@MagicWordBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
