<?php

namespace MagicWordBundle\Repository\GameType;

/**
 * MassiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MassiveRepository extends \Doctrine\ORM\EntityRepository
{
}
