parameters:
    custom_letters:
        a: 10
        b: 2
        c: 3
        d: 4
        e: 10
        f: 2
        g: 2
        h: 2
        i: 7
        j: 1
        k: 1
        l: 4
        m: 4
        n: 5
        o: 6
        p: 4
        q: 1
        r: 7
        s: 6
        t: 6
        u: 5
        v: 3
        w: 1
        x: 1
        y: 1
        z: 1
