services:
    app.user_locale_login_listener:
        class: MagicWordBundle\Listener\LoginLocaleSetter
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.locale_listener:
        class: MagicWordBundle\Listener\LocaleListener
        arguments:
                "defaultLocale": '%kernel.default_locale%'
                "tokenStorage": "@security.token_storage"
        tags:
            - { name: kernel.event_subscriber }

    app.user_registration_listener:
        class: MagicWordBundle\Listener\RegistrationListener
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
            "wordboxManager": "@mw_manager.wordbox"
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistration }
