services:
    twig.extension.get_languages:
        class: MagicWordBundle\Twig\LanguageExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    twig.extension.get_point:
        class: MagicWordBundle\Twig\LetterPointExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    twig.extension.get_connected:
        class: MagicWordBundle\Twig\UserExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
            "userManager": "@mw_manager.user"
        tags:
            - { name: twig.extension }

    twig.extension.get_word_length_point:
        class: MagicWordBundle\Twig\WordLengthPointExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    twig.extension.activity:
        class: MagicWordBundle\Twig\RoundActivityExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
            "timeManager": "@mw_manager.time"
        tags:
            - { name: twig.extension }

    twig.extension.score:
        class: MagicWordBundle\Twig\ScoreExtension
        arguments:
            "entityManager": "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
