services:
    twig.extension.get_languages:
        class: MagicWordBundle\Twig\LanguageExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extension.get_point:
        class: MagicWordBundle\Twig\LetterPointExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extension.game:
        class: MagicWordBundle\Twig\GameExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extension.get_connected:
        class: MagicWordBundle\Twig\UserExtension
        arguments: ["@doctrine.orm.entity_manager", "@mw_manager.user"]
        tags:
            - { name: twig.extension }

    twig.extension.get_word_length_point:
        class: MagicWordBundle\Twig\WordLengthPointExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extension.activity:
        class: MagicWordBundle\Twig\RoundActivityExtension
        arguments: ["@doctrine.orm.entity_manager", "@mw_manager.time"]
        tags:
            - { name: twig.extension }

    twig.extension.generalParameters:
        class: MagicWordBundle\Twig\GeneralParametersExtension
        arguments: ["@mw_manager.administration"]
        tags:
            - { name: twig.extension }

    twig.extension.score:
        class: MagicWordBundle\Twig\ScoreExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extension.wordbox:
        class: MagicWordBundle\Twig\WordboxExtension
        arguments: ["@doctrine.orm.entity_manager",  "@mw_manager.wordbox"]
        tags:
            - { name: twig.extension }
