<?php

namespace MagicWordBundle\Repository\Lexicon;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InflectionStartRepository extends \Doctrine\ORM\EntityRepository
{
    public function insert($start, $languageId)
    {
        $sql = 'INSERT INTO inflection_start (start, language) VALUES ("'.$start.'", '.$languageId.')';

        $em = $this->_em;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();

        return 1;
    }

    public function search($start, $languageId)
    {
        $sql = 'SELECT 1 FROM inflection_start WHERE MATCH(start) AGAINST (\'"'.$start.'"\'  IN NATURAL LANGUAGE MODE ) AND language = '.$languageId;

        $em = $this->_em;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();

        if (!empty($stmt->fetchAll())) {
            return true;
        };

        return false;
    }
}
