<?php

namespace MagicWordBundle\Repository\Lexicon;

/**
 * GameRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InflectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExistingWords($words, $language)
    {
        $em = $this->_em;

        $dql = 'SELECT i FROM MagicWordBundle\Entity\Lexicon\Inflection i
                WHERE i.language = :language
                AND i.cleanedContent IN (:words)';

        $query = $em->createQuery($dql);
        $query->setParameter('language', $language);
        $query->setParameter('words', $words);

        return $query->getResult();
    }

    public function getByLanguageAndContentOrCleaned($language, $content)
    {
        $em = $this->_em;
        $dql = 'SELECT i FROM MagicWordBundle\Entity\Lexicon\Inflection i
              WHERE i.language = :language
              AND (i.content = :content OR i.cleanedContent = :content)';

        $query = $em->createQuery($dql);
        $query->setParameter('language', $language)
              ->setParameter('content', $content)
              ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function findByIdRange($range)
    {
        $em = $this->_em;
        $dql = 'SELECT i FROM MagicWordBundle\Entity\Lexicon\Inflection i WHERE i.id >= :lowlimit AND i.id <= :hightlimit';

        $query = $em->createQuery($dql);
        $query->setParameter('lowlimit', $range)
              ->setParameter('hightlimit', $range + 20000);

        return $query->getResult();
    }
}
