<?php

namespace MagicWordBundle\Repository\Lexicon;

/**
 * GameRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InflectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByStartingBySubstring($substring)
    {
        $sql = 'SELECT content FROM inflection WHERE content LIKE "'.$substring.'%" LIMIT 1';
        $em = $this->_em;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();

        return $stmt->fetchAll();
    }

    public function getExistingWords($words)
    {
        $em = $this->_em;
        $dql = 'SELECT i FROM MagicWordBundle\Entity\Lexicon\Inflection i
                WHERE i.content IN('.implode(', ', array_map(array($em->getConnection(), 'quote'), $words)).')';

        $query = $em->createQuery($dql);

        return $query->getResult();
    }
}
